apiVersion: v2
appVersion: '1.0'
description: A Helm chart for Kubernetes
name: probation-offender-search
version: 0.1.1

dependencies:
  - name: generic-service
    version: 1.0.17
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
  - name: generic-prometheus-alerts
    version: 0.2.5
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
