# Values here are the same across all environments
generic-service:
  nameOverride: probation-offender-search
  serviceAccountName: probation-search

  resources:
    requests:
      cpu: 1
      memory: 512Mi

  image:
    repository: ghcr.io/ministryofjustice/probation-offender-search
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /synthetic-monitor {
          deny all;
          return 401;
        }
    tlsSecretName: probation-offender-search-cert

  env:
    SPRING_PROFILES_ACTIVE: "opensearch"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    JDK_JAVA_OPTIONS: "-javaagent:/agent/agent.jar -XX:MaxRAMPercentage=75.0"
    AWS_REGION: "eu-west-2"
    SEARCH_SUPPORTED_MAPPING_VERSION: "2"

  namespace_secrets:
    probation-offender-search:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SENTRY_DSN: "SENTRY_DSN"
    probation-search-client-credentials:
      OAUTH_CLIENT_ID: CLIENT_ID
      OAUTH_CLIENT_SECRET: CLIENT_SECRET
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: sqs_queue_name
    opensearch:
      OPENSEARCH_URIS: "url"

  allowlist:
    analyticplatform-1: 34.250.17.221/32
    analyticplatform-2: 34.251.212.33/32
    analyticplatform-3: 34.252.4.39/32
    groups:
      - internal
      - unilink_staff

generic-prometheus-alerts:
  targetApplication: probation-offender-search
