apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  OFFENDER_SEARCH_CLIENT_SECRET: {{ .Values.secrets.OFFENDER_SEARCH_CLIENT_SECRET | b64enc | quote }}
  OFFENDER_SEARCH_CLIENT_ID: {{ .Values.secrets.OFFENDER_SEARCH_CLIENT_ID | b64enc | quote }}
