---
# Environment specific values, override helm_deploy/probation-offender-search/values.yaml

generic-service:
  ingress:
    host: probation-offender-search.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.probation.service.justice.gov.uk"
    DELIUS_ENDPOINT_URL: "https://probation-search-and-delius.hmpps.service.justice.gov.uk"
    SENTRY_ENVIRONMENT: prod

  allowlist:
    delius-prod-1: 52.56.115.146/32
    delius-prod-2: 35.178.104.253/32
    delius-prod-3: 35.177.47.45/32

cron:
  SYNTHETIC_MONITOR_CRON_EXPRESSION: "*/10 * * * *"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
