# Environment specific values, override helm_deploy/probation-offender-search/values.yaml

generic-service:
  ingress:
    host: probation-offender-search-preprod.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io"
    DELIUS_ENDPOINT_URL: "https://probation-search-and-delius-preprod.hmpps.service.justice.gov.uk"
    SENTRY_ENVIRONMENT: preprod
    FLIPT_URL: https://feature-flags-preprod.hmpps.service.justice.gov.uk

  allowlist:
    delius-pre-prod-1: 52.56.240.62/32
    delius-pre-prod-2: 18.130.110.168/32
    delius-pre-prod-3: 35.178.44.184/32

cron:
  SYNTHETIC_MONITOR_CRON_EXPRESSION: "*/10 * * * *"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications

  # Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
  businessHoursOnly: true
