---
# Environment specific values, override helm_deploy/probation-offender-search/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: probation-offender-search-staging.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.stage.delius.probation.hmpps.dsd.io"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    delius-aws-1: "3.10.104.193/32"
    delius-aws-2: "3.11.26.150/32"
    delius-aws-3: "18.130.189.137/32"

cron:
  SYNTHETIC_MONITOR_CRON_EXPRESSION: "*/10 * * * *"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
