generic-service:
  ingress:
    host: probation-offender-search-preprod.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io"
    SENTRY_ENVIRONMENT: preprod

  allowlist:
    delius-pre-prod-1: 52.56.240.62/32
    delius-pre-prod-2: 18.130.110.168/32
    delius-pre-prod-3: 35.178.44.184/32
    analyticplatform-1: 34.250.17.221/32
    analyticplatform-2: 34.251.212.33/32
    analyticplatform-3: 34.252.4.39/32
    undefined: internal/32
    groups: []

cron:
  SYNTHETIC_MONITOR_CRON_EXPRESSION: "*/10 * * * *"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications

  # Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
  businessHoursOnly: true
