name: Formatting

on:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Format code
        uses: ministryofjustice/hmpps-probation-integration-services/.github/actions/format-code@main