name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "29 3 * * MON-FRI" # Every weekday at 03:29 UTC
jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@c2a23fcb9a0ce8f98145230d4fe930bd9008d12b # v2.14.5
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
