name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "29 3 * * MON-FRI" # Every weekday at 03:29 UTC
jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@2a7bb1a9bdaa0ebad11f03538dbcf396ba3b7779 # v2.19.0
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
