name: Security veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "50 3 * * 1" # Every Monday at 03:50 UTC
jobs:
  security-veracode-policy-check:
    name: Project security veracode policy scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@3099514d634a6b7bcd443ea82fde249861702515 # v2.17.0
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
