name: Suppress-Trivy

on:
  push:
    branches:
      - PI-516-GHA_suppress_trivy

jobs:
  issue_commented:
    name: Issue Comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh issue edit $ISSUE_URL --add-label "wontfix"
          echo A comment on issue $NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          NUMBER: ${{ github.event.issue.number }}