name: Suppress-Trivy - write to file

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      cve_id:
        description: CVE ID
        type: string
        required: true

jobs:
  build:
    if: github.event_name=='workflow_dispatch' || (startsWith(github.event.comment.body, 'Suppress') && startsWith(github.event.issue.title, 'CVE-'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set CVE from Issue Title automatically
        if: github.event_name=='issue_comment'
        run: echo cve_id=${{ github.event.issue.title }} >> $GITHUB_ENV

      - name: Set CVE from manual input
        if: github.event_name=='workflow_dispatch'
        run: echo cve_id=${{ inputs.cve_id }} >> $GITHUB_ENV


      - name: Overwrite file
        run: echo -e "\n#${{ github.event.comment.body }}\n${{ env.cve_id }}" >> .trivyignore

      - name: Upload file and create pull request
        run: |
          git switch -c suppress/${{ env.cve_id }}
          git push origin suppress/${{ env.cve_id }}
          gh api --method PUT /repos/ministryofjustice/probation-offender-search/contents/.trivyignore \
            --field message="Suppress ${{ env.cve_id }}" \
            --field content=@<( base64 -i .trivyignore ) \
            --field branch='suppress/${{ env.cve_id }}' \
            --field sha="$( git rev-parse 'suppress/${{ env.cve_id }}:.trivyignore' )"
          gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ github.token }}
