##get issue name
#store as variable
#use variable in write 2 file comment append
#no need to make a PR OR BRANCH as workflow can auto append it in the workflow
#Separate cron job to check if issue with CVE prefix is stale for 7 days
#remove issue



name: Suppress-Trivy - write to file

on:
  push:
    branches:
      - PI-516-GHA_suppress_trivy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List Issue
        id: get_issue_list
        run: echo $AUTHOR $ISSUE_NAME
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AUTHOR: ${{ github.actor }}
            BRANCH_NAME: ${{ github.ref_name }}
            ISSUE_NAME: ${{ github.event.issue.title }}


      - name: Overwrite file
        uses: DamianReeves/write-file-action@master
        with:
          path: .trivyignore
          write-mode: append
          contents: |
            ${{ github.ref_name }}
            ${{ github.event.issue.title }}


      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: ${{ github.actor }}
          branch: PI-516-GHA_suppress_trivy
          force: true
          message: 'Appended by ${author_name} GitHub Actions - ${date}'