name: Suppress-Trivy

on:
  push:
    branches:
      - PI-516-GHA_suppress_trivy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: .trivyignore
          write-mode: append
          contents: |
            ${{ github.GITHUB_HEAD_REF }}

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: PI-516-GHA_suppress_trivy
          force: true
          message: 'Overwritten by Github Actions - ${date}'