name: Suppress-Trivy - write to file

on:
  push:
    branches:
      - PI-516-GHA_suppress_trivy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get & Set Branch Variable
        id: get_branch_name
        run: |
          echo ${GITHUB_REF##*/}=Branch >> $GITHUB_OUTPUT

        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AUTHOR: ${{ github.actor }}
#            GITHUB_REF: ${{ github.ref }}

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: .trivyignore
          write-mode: append
          contents: >
            This was made 
            through ghactions
            ${{ steps.get_branch_name.outputs.Branch }}

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: PI-516-GHA_suppress_trivy
          force: true
          message: 'Appended by GitHub Actions - ${date}'