name: Suppress-Trivy - write to file

on:
  push:
    branches:
      - PI-516-GHA_suppress_trivy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get & Set Branch Variable
        id: get_branch_name
        run: |
          echo $BRANCH_NAME by $AUTHOR
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AUTHOR: ${{ github.actor }}
            BRANCH_NAME: ${{ github.ref_name }}

      - name: Overwrite file
        uses: DamianReeves/write-file-action@vmaster
        with:
          paths: /.trivyignore
          write-mode: append
          contents: |
            ${{ github.ref_name }}


      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: ${{ github.actor }}
          branch: PI-516-GHA_suppress_trivy
          force: true
          message: 'Appended by ${author_name} GitHub Actions - ${date}'