name: Suppress-Trivy - write to file

on:
  push:
    branches:
      - PI-516-GHA_suppress_trivy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

#      - name: Get & Set Variables
#        run: echo "##[set-output name=branch;]$(echo $GITHUB_REF#refs/heads/})"
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#            AUTHOR: ${{ github.actor }}

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: .trivyignore
          write-mode: append
          contents: >
             Actions 
              appended code
            ${{ github.actor }}
            ${{ github.ref##*/ }}