name: Scan image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC

jobs:
  trivy:
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@ca5e8662ec075a9ec232f93e003fffd451a9bda8 # v1
    with:
      channel_id: probation-integration-notifications
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}