name: Scan image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:30 UTC

jobs:
  trivy:
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@575b0afab064016521c4b1671c9221b9f8fc3039 # v1
    with:
      channel_id: probation-integration-notifications
    secrets:
      HMPPS_SRE_SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}